# Generated by Django 5.0.1 on 2026-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('Grooming', 'Grooming'), ('Vaccination', 'Vaccination'), ('Checkup', 'General Checkup'), ('Visit', 'Pet Visit')], max_length=50),
        ),
    ]
